version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  web:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    environment:
      DEBUG: 'true'
      MONGO_NAME=mongo
      MONGO_USER=mongo
      MONGO_PASSWORD=mongo
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-django:
  web-static:
  redisdata:
